import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./tailwind.css";

// fonts files

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const fontsClassName = `${geistSans.variable} ${geistMono.variable}`;

// seo metadata

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// main comp

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${fontsClassName} antialiased`}>
        {children}
      </body>
    </html>
  );
}
