import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./tailwind.css";

import { GlobalNextServerDataProvider } from "@/components/views/global-next-server-data/server-component";

// fonts files

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// seo metadata

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// main comp

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GlobalNextServerDataProvider>
          {children}
        </GlobalNextServerDataProvider>
      </body>
    </html>
  );
}
