import type { Metadata } from "next";
import "./tailwind.css";

import { ds } from "@/lib/ds";
import { GlobalNextServerDataProvider } from "@/components/views/global-next-server-data/server-component";

// seo metadata

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// main comp

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ds.bodyClassName} antialiased`}
      >
        <GlobalNextServerDataProvider>
          {children}
        </GlobalNextServerDataProvider>
      </body>
    </html>
  );
}
